name: read_aloud_front
description: "Read Aloud Front"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  provider: ^6.1.4
  http: ^1.2.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/data/
    - assets/demo.mp3
      
